meta:
  title: Okta API Reference
  description: The best API documentation ever.
  siteUrl: https://developer.okta.com
  keywords: okta, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./images/logo.svg
  altText: Okta Developer
toc:
  enable: true
oasDefinitions:
  okta-management: ./openapi/management.yaml
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:
  - label: Developer Docs
    href: https://developer.okta.com
  - label: Sign in to Okta
    href: https://login.okta.com
  - search: true

footer:
  copyrightText: Copyright Â© 2021 Okta.
  columns:
    - group: CONTACT & LEGAL
      items:
        - label: Contact our team
          href: 'https://www.okta.com/contact/'
        - label: Contact sales
          href: 'https://www.okta.com/contact-sales/'
        - label: Terms & Conditions
          href: 'https://developer.okta.com/terms/'
        - label: Privacy Notice
          href: 'https://www.okta.com/privacy-policy/'
    - group: MORE INFO
      items:
        - label: Pricing
          href: 'https://www.okta.com/pricing/'
        - label: Integrate with Okta
          href: 'https://developer.okta.com/okta-integration-network/'
        - label: Change log
          href: 'https://developer.okta.com/docs/release-notes/'
        - label: 3rd-party notes
          href: 'https://developer.okta.com/3rd_party_notices/'
        - label: Auth0 platform
          href: 'https://auth0.com/developers'
